713-gradcam
Project-MONAI/MONAI pull request #1303
Opened 2020-11-30 14:57 UTC by wyli

Signed-off-by: Wenqi Li <wenqil@nvidia.com>

Fixes #713; fixes #1212 

### Description
A few sentences describing the changes proposed in this pull request.

### Status
**Work in progress**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh --codeformat --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

2020-11-30 17:29 UTC, ahatamiz requested changes

2020-11-30 17:29 UTC, ahatamiz commented on monai/visualize/class_activation_maps.py
> +        return self.norm_features(map)
Normalization not needed here

2020-11-30 17:29 UTC, ahatamiz commented on monai/visualize/class_activation_maps.py
> +#         cam_img = cam_computer(img_tensor)[0].detach().cpu().numpy()
Normalizing cam_img is preferred here. Something as simple as the following should work:

`cam_img = (cam_img-cam_img.min())/ cam_img.max()`

2020-11-30 20:11 UTC, wyli commented
thanks @ahatamiz I've updated the modules, I'll add a few unit tests. do you have a use case in 3D by any chance?

2020-11-30 20:19 UTC, ahatamiz commented
> thanks @ahatamiz I've updated the modules, I'll add a few unit tests. do you have a use case in 3D by any chance?

Great work @wyli !  I don't have a trained 3D use case right now.. but maybe we can use one of the COVID models for classification ?

2020-12-01 18:11 UTC, wyli commented
added modules and tests for:
- cam
![cam](https://user-images.githubusercontent.com/831580/100779637-976bc980-3400-11eb-8def-2120363ab596.png)
- gradcam
![gradcam](https://user-images.githubusercontent.com/831580/100779644-989cf680-3400-11eb-810b-d3d04f540956.png)
- gradcam++
![gradcam++](https://user-images.githubusercontent.com/831580/100779652-99ce2380-3400-11eb-97e8-bd718139896e.png)

2020-12-02 05:43 UTC, Nic-Ma approved these changes
Thanks for your great work, this new feature looks good to me.
@ericspod do you have any more comments from a researcher's view?

Thanks.

2020-12-02 09:31 UTC, Nic-Ma commented
Hi @wyli , and BTW, I think this is very cool a new feature, could you please help also develop a tutorial notebook for it?

Thanks.

2020-12-02 09:40 UTC, wyli commented
> Hi @wyli , and BTW, I think this is very cool a new feature, could you please help also develop a tutorial notebook for it?
> 
> Thanks.

that would be nice but I don't have a good quality 3d model, do you have access to any classification model?

2020-12-02 09:46 UTC, Nic-Ma commented
Can we use IXI dataset to train a model? Actually, I am curious which part of the feature map indicates the gender in IXI.
Thanks.

2020-12-02 09:49 UTC, wyli commented
> Can we use IXI dataset to train a model? Actually, I am curious which part of the feature map indicates the gender in IXI.
> Thanks.

the training is a short demo with only a few examples, don't think visualisation will make sense..

2020-12-02 09:52 UTC, Nic-Ma commented
OK, then I don't have any better dataset for reference. Maybe @ericspod knows more?
Thanks.

2020-12-02 10:02 UTC, merged

2020-12-02 10:04 UTC, wyli commented
I create a ticket to track the progress of the demo https://github.com/Project-MONAI/tutorials/issues/76