3694 loss function as cumulative metric
Project-MONAI/MONAI pull request #5513
Opened 2022-11-11 16:08 UTC by wyli

Signed-off-by: Wenqi Li <wenqil@nvidia.com>

Fixes #3694

### Description
adds a wrapper for loss function:
```py
dice_loss = DiceLoss(include_background=True)
loss_metric = LossMetric(loss_fn=dice_loss)
```
so that `loss_metric` it can be used as a metric in:
https://github.com/Project-MONAI/MONAI/blob/b030839e98e6a00c1ab0e53545f60b62dc4da4a4/monai/handlers/ignite_metric.py#L32

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [x] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [x] Quick tests passed locally by running `./runtests.sh --quick --unittests  --disttests`.
- [x] In-line docstrings updated.
- [x] Documentation updated, tested `make html` command in the `docs/` folder.

2022-11-12 02:33 UTC, Nic-Ma commented
Hi @wyli ,

Users can use the ignite metric directly:
https://github.com/pytorch/ignite/blob/master/ignite/metrics/loss.py
Just like how we use the `Accuracy` of ignite.
CC @vfdev-5 .

Thanks.

2022-11-12 07:49 UTC, wyli commented
@Nic-Ma yes I'm aware of that, the assumptions on loss_fn is stronger there: -- requiring both y_pred and y, and -- the output must be a single value and --must be used with an ignite engine... 

In our case, previously I thought the cumulative average is good enough, https://github.com/Project-MONAI/MONAI/blob/89684d677f6c93c6fbd023a614c07485c5223557/monai/metrics/cumulative_average.py#L21
But it doesn't seem to work with IgniteMetric handler.

2022-11-16 00:50 UTC, myron requested changes
> assumptions on loss_fn is stronger there: -- requiring both y_pred and y, and -- the output must be a single value and --must be used with an ignite engine...

@wyli  thanks for the PR , but I don't think this is what people are asking for in the issue https://github.com/Project-MONAI/MONAI/issues/3694, they did not ask for Ignite support. (unless I misunderstand).  

And currently we can currently use 

```
ac = CumulativeAverage()
loss_value = someloss(x,y)
ac.append(ac)
```

this will work even if loss_value is an array/list/tensor (and removes nans).  I'll clarify what people in the issue are actually asking, unless this PR addresses something else

2022-11-16 08:08 UTC, wyli commented
Hi @myron, as I mentioned in the description of this PR, it's about using the loss value within `monai.handlers.IgniteMetric`. `CumulativeAverage` is not compatible within that class. If you are not sure about the PR, we can discuss, but please don't block it using your admin permission.

2022-11-16 08:20 UTC, wyli commented
Hi @Nic-Ma  do you have any further comments here?

2022-11-16 08:29 UTC, Nic-Ma approved these changes

2022-11-16 08:30 UTC, Nic-Ma commented on monai/metrics/loss_as_metric.py
> +# Copyright (c) MONAI Consortium
As the metric name is `LossMetric`, I would suggest to change the file name to `loss_metric.py`.
What do you think?

Thanks.

2022-11-16 08:30 UTC, Nic-Ma commented
> @Nic-Ma yes I'm aware of that, the assumptions on loss_fn is stronger there: -- requiring both y_pred and y, and -- the output must be a single value and --must be used with an ignite engine...
> 
> In our case, previously I thought the cumulative average is good enough,
> 
> https://github.com/Project-MONAI/MONAI/blob/89684d677f6c93c6fbd023a614c07485c5223557/monai/metrics/cumulative_average.py#L21
> 
> 
> But it doesn't seem to work with IgniteMetric handler.

OK, that makes sense.

Thanks.

2022-11-16 18:41 UTC, myron approved these changes

2022-11-16 18:51 UTC, myron commented
> Hi @myron, as I mentioned in the description of this PR, it's about using the loss value within `monai.handlers.IgniteMetric`. `CumulativeAverage` is not compatible within that class. If you are not sure about the PR, we can discuss, but please don't block it using your admin permission.

thank you for the reply. In the PR description on the top , it says that it fixes https://github.com/Project-MONAI/MONAI/issues/3694
In my understanding  it does not fix that issue, since people were asking for something else.  Hence, I left the review and requested the change.  Do you prefer me not leaving reviews at all or not requesting changes?  ps: I changed the review status to approve.

2022-11-16 20:27 UTC, wyli commented
/build

2022-11-16 20:29 UTC, wyli commented
/build

2022-11-16 21:15 UTC, merged