Recursive Item Mapping for Nested Lists in Compose
Project-MONAI/MONAI pull request #8187
Opened 2024-11-01 07:13 UTC by KumoLiu

Fixes #8186.

### Description

A few sentences describing the changes proposed in this pull request.

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests  --disttests`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

2025-01-03 18:51 UTC, ziw-liu commented
Hi @KumoLiu and thanks for the fix! Is this branch ready for testing?

2025-01-06 04:24 UTC, KumoLiu commented
> Hi @KumoLiu and thanks for the fix! Is this branch ready for testing?

Hi @ziw-liu, the current fix solves the problem you raised, but it leads to something else, such as not having a handle for those who don't want a recursive map. I still need to revise this PR further. Thanks.

2025-01-17 15:44 UTC, ericspod commented
@atbenmurray please review this as well as we just discussed.

2025-01-24 13:58 UTC, atbenmurray requested changes
Looking at it, map_items=True has always acted as map_items=1, so at least we aren't changing the behaviour of using bool and now the int indicates the _maximum_ amount of nesting that can be expected. This would also be the case if we use a multi sample transform after a multi sample transform. Its a bit opaque semantically that we do this and might benefit from additional commenting.

2025-01-24 13:58 UTC, atbenmurray commented on monai/transforms/transform.py
> +                return [_apply_transform(transform, item, unpack_items, lazy, overrides, log_stats) for item in data]
```suggestion
        map_items_ = int(map_items) if isinstance(map_items, bool) else map_items
        if isinstance(data, (list, tuple)) and map_items_ > 0:
            return [
                apply_transform(transform, item, map_items - 1, unpack_items, log_stats, lazy, overrides)
                for item in data
            ]
```

Simplified logic so that bool is considered a user friendly version of 1.

2025-01-24 14:22 UTC, KumoLiu commented
Hi @atbenmurray, thanks for the suggestion, I enhance the docstring in the latest commit. Please help take a look whether it looks clearer to you.

2025-01-24 14:24 UTC, atbenmurray requested changes
minor tweak required due to a typo in my earlier suggestion

2025-01-24 14:24 UTC, atbenmurray commented on monai/transforms/transform.py
> +                apply_transform(transform, item, map_items - 1, unpack_items, log_stats, lazy, overrides)
```suggestion
                apply_transform(transform, item, map_items_ - 1, unpack_items, log_stats, lazy, overrides)
```
My bad, I should have copied the code from my test repo

2025-02-12 15:20 UTC, ericspod commented
Hi @KumoLiu we have a minor conflict here but otherwise I think we're good?

2025-02-12 15:48 UTC, KumoLiu commented
/build

2025-02-12 19:10 UTC, merged